package notesClassesInterfaces;

class James			// class inside a .java file
James.java			// Java source code file, contains class James
james.class			// Java bytecode generated by the complier

/* 
 * comments also look like this
 */

//	
// or this
//

General Project Structure:
	
	Package statement			// defines the directory structure of the project
	Import Statement			// 
	
	class declaration			// must be lowercase c
		Variables				// proporties of the class
								// 		Instance variables = each object instance has its own
								// 		Class variable = all classes share the same common ones
		Constructors			// Initialses the objects of a class
		Methods					// Behaviors of the class
		Nested classes			// 
		Nested interfaces		// 
		Enum					// 
		
	interface declaration		// A group of related methods and constants.
								// lowercase i
								// A method in an interface cannot define implementation
								// The interface specifies contract for class to implement
								//
	